Ibmmqconnector
wso2-incubator/esb-connector-ibmmq pull request #1
Opened 2017-06-29 09:13 UTC by hasithajayasundara

**ibm-mq-connector for wso2 esb**

2017-07-02 08:25 UTC, nadeeshaan commented on src/test/resources/testng.xml
> + ~  Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Please correct the license header to 2017 license header

2017-07-02 08:29 UTC, nadeeshaan commented on src/main/assembly/assemble-connector.xml
> +   Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Please correct the license header to 2017 license header

2017-07-02 08:30 UTC, nadeeshaan commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +/**
Remove the current Java Doc and add a descriptive one

2017-07-02 08:31 UTC, nadeeshaan commented on src/main/java/org/wso2/carbon/esb/connector/MQConstants.java
> +
Remove the current Java Doc and add a descriptive one

2017-07-02 08:31 UTC, nadeeshaan commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> + * Created by hasitha on 6/30/17.
Remove the current Java Doc and add a descriptive one

2017-07-02 14:11 UTC, hasithajayasundara commented on src/test/resources/testng.xml
> + ~  Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Done.!

2017-07-02 14:12 UTC, hasithajayasundara commented on src/main/assembly/assemble-connector.xml
> +   Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Done.!

2017-07-02 14:12 UTC, hasithajayasundara commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +/**
Done.!

2017-07-02 14:12 UTC, hasithajayasundara commented on src/main/java/org/wso2/carbon/esb/connector/MQConstants.java
> +
Done.!

2017-07-06 04:32 UTC, hmrajas commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +
Please add wso2 licence header to each file

2017-07-06 19:30 UTC, hasithajayasundara commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +
Done.!

2017-08-03 04:20 UTC, djkevincr requested changes

2017-08-03 04:20 UTC, djkevincr commented on org.wso2.carbon.esb.connector.ibmmqconnector.iml
> +<?xml version="1.0" encoding="UTF-8"?>
We need remove this idea generated files.

2017-08-03 04:25 UTC, djkevincr commented on pom.xml
> +
Please remove this unnecessary new lines.

2017-08-03 04:25 UTC, djkevincr commented on pom.xml
> +
Please remove this unnecessary new lines.

2017-08-03 04:26 UTC, djkevincr commented on src/main/assembly/filter.properties
> +
Please remove this unnecessary new lines.

2017-08-03 04:28 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +import static com.ibm.mq.constants.CMQC.*;
Please remove this wild card imports, do this imports separately.

2017-08-03 04:31 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +    public int getmaxConnections() {
Please use Javadoc proper standards to document all the public methods.

2017-08-03 04:32 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +    private String queue;
Please document all the parameters.

2017-08-03 04:36 UTC, hasithajayasundara commented on org.wso2.carbon.esb.connector.ibmmqconnector.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Done

2017-08-03 04:43 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +import java.util.concurrent.*;
Please remove these wild card imports.

2017-08-03 04:44 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +
Please remove these unnecessary new lines.

2017-08-03 04:44 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +
Please remove these unnecessary new lines.

2017-08-03 04:44 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +
Please remove these unnecessary new lines.

2017-08-03 04:52 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    MQConnectionBuilder(MessageContext msg) {
Shall we change the method signature to MQConnectionBuilder(MQConfiguration config); and extract MQConfiguration from message context from earlier step.

2017-08-03 04:54 UTC, hasithajayasundara commented on pom.xml
> +
done

2017-08-03 04:55 UTC, hasithajayasundara commented on pom.xml
> +
done

2017-08-03 04:55 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +            queueManager = getQueueManager(config.getHost(), config.getChannel(), config.getPort());
Please improve logging for,
[1] retry with retry interval.
[2] Successful queue manager return.
[3] Un-Successful queue manager return.

2017-08-03 05:12 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    private MQQueueManager queueManager;
Builder classes usually not maintain state inside class. Shall we remove this class variable and use utility methods inside the this builder class.

2017-08-03 05:14 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +            return null;
Please use proper logging for these cases, if logging is not needed you may add comment saying this is expected scenario and we will return 'null', 'null' will be properly handled at higher layer.

2017-08-03 05:16 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +public class MQConnectionBuilder {
Shall we rename this to MQConnectionUtils and use all public static methods?

2017-08-03 05:18 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +        try {
closeQueueManager(MQQueueManager queueManager);

2017-08-03 05:18 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    public void closeConnection() {
closeQueueManager(MQQueueManager queueManager);

2017-08-03 05:29 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    MQSimpleConnectionManager customizedPool(long timeout, int maxConnections, int maxunusedConnections) {
Please add this as a private method.

2017-08-03 05:32 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    public MQConfiguration getConfig() {
getConfig(MessageContext context)

2017-08-03 05:33 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQConnectionBuilder.java
> +    public SSLContext createSSLContext() {
Please add this as static method.

2017-08-03 05:36 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +import com.ibm.mq.*;
Please remove all the wild card imports and do imports separately.

2017-08-03 05:37 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +import static com.ibm.mq.constants.CMQC.*;
Please remove all the wild card imports and do imports separately.

2017-08-03 05:39 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQConfiguration config;
Having MQConnectionBuilder, MQConfiguration will not work for concurrent cases. We need to have some sort pooling mechanism to reuse IBM-MQ connections.

2017-08-03 05:44 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            if(connectionBuilder==null || connectionBuilder.getManager()==null) {
if( - This is not formatted properly.

2017-08-03 05:46 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            log.info("Message received at ibm-mq connector");
May be we should use debug here, otherwise we ll be flooded with these info logs.

2017-08-03 05:52 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +                connectionBuilder = new MQConnectionBuilder(messageContext);
First create MQConfiguration from messageContext properties and then pass that to utility method to MQConnectionUtils.getQueueManaget(MQConfiguration config) to retrieve queue managed from the pool.

2017-08-03 05:53 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +                log.error("Error in publishing message");
Please make this log more informative, what is the exact reason failed publishing the message.

2017-08-03 05:54 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +                log.info("queue initialized");
This should be a debug log.

2017-08-03 05:55 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQQueue setQueue(MQConnectionBuilder connectionBuilder, MQConfiguration config) {
This should be private static method.

2017-08-03 05:59 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            return null;
Can we continue the flow getting the exception from here? Is this null case handled properly at higher layer. Or do we need to throw/propagate this to higher layer?

2017-08-03 05:59 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQMessage buildDatagramOrReplyMessage(MQConfiguration config, String queueMessage) {
These methods should be private.

2017-08-03 06:01 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            log.info("Error creating mq message" + e);
This should be error, log.error("Error creating Datagram/Reply mq message" + e);

2017-08-03 06:01 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQMessage buildRequestMessageandGetResponse(MQConfiguration config, String queueMessage) {
This method should be private.

2017-08-03 06:02 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            log.info("Error creating mq message" + e);
log.error("Error creating Request/Responce mq message" + e);

2017-08-03 06:07 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +        return mqMessage;
I think for all these message types, it s better to throw the error to higher layer and from there it should be wrapped as ConnectionException. Returning message as empty and handle that as a generic one, one thing we loose information from lower layer why it is failed.

2017-08-03 06:14 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    void getReplyMessge(final MQQueue replyQueue, MQConfiguration config) {
I think can get rid of this method by pointing, ibm-mq inbound to reply queue. Handling Listening part a connector in not good IMO.

2017-08-03 06:15 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQMessage buildReportMessage(MQConfiguration config, String queueMessage) {
This should be private static method.

2017-08-03 06:16 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    void getReportMessage(final MQQueue replyQueue, MQConfiguration config) {
I think can get rid of this method by pointing, ibm-mq inbound to reply queue. Handling Listening part a connector in not good IMO.

2017-08-03 06:17 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    String reportStr(int code) {
This should be private static.

2017-08-03 06:17 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +    MQQueue setReplyQueue(MQConnectionBuilder connectionBuilder, MQConfiguration config) {
This should be private static.

2017-08-03 06:19 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishQueue.java
> +            return null;
Returning null and handle error as generic, we will be loosing information why this got failed. It s better if we could throw this exception to higher layer and handle over there.

2017-08-03 06:20 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +    MQConnectionBuilder connectionBuilder;
This will not work for the concurrent cases. Please see related comments for queue, same goes here as well.

2017-08-03 06:21 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +            return null;
Returning null and handle error as generic, we will be loosing information why this got failed. It s better if we could throw this exception to higher layer and handle over there.

2017-08-03 06:23 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +            log.info("Message received at ibm-mq connector");
log.debug();

2017-08-03 06:23 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +            config = connectionBuilder.getConfig();
We need to use utility methods, as mentioned for the queue.

2017-08-03 06:25 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +                log.error("Error in publishing message");
(topic == null || mqMessage == null), returning null and logging as generic error is not a god practice. It s better if we could catch the exception here and propagate as ConnectException and end the flow from here.

2017-08-03 06:26 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +                log.info("topic initialized");
May be we should use debug log here.

2017-08-03 06:27 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +            log.info("Error creating mq message" + e);
Returning null and handle error as generic, we will be loosing information why this got failed. It s better if we could throw this exception to higher layer and handle over there.

2017-08-03 06:28 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQReportConstants.java
> +    public static final String MQFB_EXPIRATION = "Feedback indicating that the message was discarded because it had not been removed from the destination queue before its expiry time had elapsed";
Since we point a separate reply queue, handle this separately, we do not need to decode this message codes.

2017-08-03 06:29 UTC, djkevincr commented on src/test/java/org/wso2/carbon/connector/ibmmqIntegrationTest.java
> +public class ibmmqIntegrationTest extends ConnectorIntegrationTestBase {
IbmmqIntegrationTest

2017-08-03 06:32 UTC, djkevincr commented on src/main/resources/publishqueue/component.xml
> +<?xml version="1.0" encoding="UTF-8"?>
com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar these jar files should be remove. Please remove all the proprietary IBM binary files from the PR.

2017-08-03 06:34 UTC, djkevincr commented
Please note you should remove all the proprietary IBM binary files committed from the PR. 
com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar

2017-08-03 13:06 UTC, malakasilva requested changes

2017-08-03 13:06 UTC, malakasilva commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +        if (msg.getProperty(MQConstants.PORT) != null) {
Can you set the default value first. Can reduce number of lines.

2017-08-03 13:06 UTC, malakasilva commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +        if (msg.getProperty(MQConstants.PORT) != null) {
EG:
 +        this.port = 1414;
 +        if (msg.getProperty(MQConstants.PORT) != null) {
 +            this.port = Integer.valueOf((String) msg.getProperty(MQConstants.PORT));
 +        }

2017-08-03 13:06 UTC, malakasilva commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +    MQConfiguration(MessageContext msg) {
Give a proper name for msg.

2017-08-03 13:06 UTC, malakasilva commented on src/main/java/org/wso2/carbon/esb/connector/MQConfiguration.java
> +        if (messageTypeString != null) {
No point doing this. Can you directly assign.

2017-08-03 19:50 UTC, djkevincr commented on src/main/java/org/wso2/carbon/esb/connector/MQPublishTopic.java
> +            log.info("Error creating mq message" + e);
log.info("Error creating mq message" , e);

2017-08-08 06:00 UTC, riyafa commented
What if we have few well explained commits in the PR? You may squash commits in the following manner:
https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

2024-02-01 20:32 UTC, closed without merging